// Central Bengali string dictionary for iCANBD.
// Every visible piece of UI copy MUST come from here.

export const t = {
  brand: {
    name: "iCANBD",
    tagline: "আপনার শিক্ষার সঙ্গী",
  },
  nav: {
    home: "হোম",
    courses: "কোর্সসমূহ",
    products: "প্রোডাক্ট",
    gallery: "গ্যালারি",
    notices: "নোটিশবোর্ড",
    contact: "যোগাযোগ",
    about: "আমাদের সম্পর্কে",
    login: "লগইন",
    register: "রেজিস্টার করুন",
    dashboard: "ড্যাশবোর্ড",
    profile: "প্রোফাইল",
    logout: "লগআউট",
    menu: "মেনু",
  },
  footer: {
    quickLinks: "দ্রুত লিংক",
    support: "সহায়তা",
    contactInfo: "যোগাযোগ তথ্য",
    privacy: "গোপনীয়তা নীতি",
    refund: "রিফান্ড নীতি",
    rights: "© ২০২৬ iCANBD। সর্বস্বত্ব সংরক্ষিত।",
  },
  auth: {
    loginTitle: "আপনার অ্যাকাউন্টে লগইন করুন",
    loginSubtitle: "শেখা চালিয়ে যেতে নিচের তথ্য দিন",
    registerTitle: "নতুন অ্যাকাউন্ট তৈরি করুন",
    registerSubtitle: "মাত্র কয়েক ধাপে যোগ দিন",
    fullName: "পূর্ণ নাম",
    email: "ইমেইল",
    phone: "মোবাইল নম্বর",
    password: "পাসওয়ার্ড",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    loginButton: "লগইন করুন",
    registerButton: "রেজিস্টার করুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    haveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    noAccount: "অ্যাকাউন্ট নেই?",
    loginHere: "এখানে লগইন করুন",
    registerHere: "এখানে রেজিস্টার করুন",
    forgotTitle: "পাসওয়ার্ড পুনরুদ্ধার",
    forgotSubtitle: "আপনার ইমেইল দিন, আমরা একটি লিংক পাঠাবো",
    sendLink: "লিংক পাঠান",
    backToLogin: "লগইন পেজে ফিরে যান",
    resetTitle: "নতুন পাসওয়ার্ড সেট করুন",
    resetSubtitle: "নতুন পাসওয়ার্ড দিন",
    updatePassword: "পাসওয়ার্ড আপডেট করুন",
    loggingIn: "লগইন হচ্ছে...",
    registering: "রেজিস্টার হচ্ছে...",
    sending: "পাঠানো হচ্ছে...",
    updating: "আপডেট হচ্ছে...",
  },
  toast: {
    loginSuccess: "সফলভাবে লগইন হয়েছে",
    loginFailed: "লগইন ব্যর্থ হয়েছে",
    registerSuccess: "অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে",
    registerFailed: "রেজিস্ট্রেশন ব্যর্থ হয়েছে",
    logoutSuccess: "সফলভাবে লগআউট হয়েছে",
    resetEmailSent: "পাসওয়ার্ড রিসেট লিংক পাঠানো হয়েছে",
    resetEmailFailed: "লিংক পাঠাতে ব্যর্থ",
    passwordUpdated: "পাসওয়ার্ড আপডেট হয়েছে",
    passwordMismatch: "পাসওয়ার্ড মিলছে না",
    requiredField: "এই ক্ষেত্রটি পূরণ করুন",
    invalidEmail: "সঠিক ইমেইল দিন",
    weakPassword: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে",
  },
  dashboard: {
    overview: "ওভারভিউ",
    myCourses: "আমার কোর্স",
    welcome: "স্বাগতম",
    title: "শিক্ষার্থী ড্যাশবোর্ড",
  },
  admin: {
    title: "অ্যাডমিন প্যানেল",
    dashboard: "ড্যাশবোর্ড",
    courses: "কোর্স ব্যবস্থাপনা",
    products: "প্রোডাক্ট ব্যবস্থাপনা",
    orders: "অর্ডার",
    students: "শিক্ষার্থী",
    pageBuilder: "পেজ বিল্ডার",
    settings: "সেটিংস",
  },
  builder: {
    title: "হোমপেজ পেজ বিল্ডার",
    subtitle: "সেকশন যোগ করুন, সাজান ও সম্পাদনা করুন।",
    addSection: "সেকশন যোগ করুন",
    chooseSection: "একটি সেকশন নির্বাচন করুন",
    activeSections: "সক্রিয় সেকশনসমূহ",
    noSections: "এখনো কোনো সেকশন নেই। উপরে থেকে যোগ করুন।",
    edit: "সম্পাদনা",
    delete: "ডিলিট",
    show: "দেখান",
    hide: "লুকান",
    confirmDeleteTitle: "সেকশন ডিলিট করবেন?",
    confirmDeleteDesc: "এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।",
    cancel: "বাতিল",
    confirm: "নিশ্চিত করুন",
    saveDraft: "সংরক্ষণ করুন",
    publish: "প্রকাশ করুন",
    saving: "সংরক্ষণ হচ্ছে...",
    publishing: "প্রকাশ হচ্ছে...",
    saved: "সফলভাবে সংরক্ষিত হয়েছে",
    published: "সফলভাবে প্রকাশিত হয়েছে",
    saveFailed: "সংরক্ষণ ব্যর্থ হয়েছে",
    previewPlaceholder: "কোনো সেকশন নির্বাচিত নেই — পেজের লাইভ প্রিভিউ নিচে।",
    livePreview: "লাইভ প্রিভিউ",
    sectionEditor: "সেকশন এডিটর",
    backToPreview: "প্রিভিউতে ফিরে যান",
    addItem: "আইটেম যোগ করুন",
    removeItem: "সরান",
    fields: {
      heading: "শিরোনাম",
      subheading: "উপশিরোনাম",
      buttonText: "বাটন টেক্সট",
      buttonLink: "বাটন লিংক",
      backgroundImage: "পটভূমি ছবি (URL)",
      backgroundType: "পটভূমির ধরন",
      backgroundColor: "পটভূমির রং",
      overlayOpacity: "ওভারলে অপাসিটি",
      textAlign: "টেক্সট এলাইনমেন্ট",
      icon: "আইকন",
      value: "সংখ্যা",
      label: "লেবেল",
      count: "কতটি দেখাবে",
      source: "সোর্স",
      showSeeAll: "“সব দেখুন” বাটন দেখাবে",
      title: "শিরোনাম",
      description: "বিবরণ",
      quote: "উক্তি",
      name: "নাম",
      course: "কোর্সের নাম",
      rating: "রেটিং",
      avatar: "ছবি (URL)",
      autoSlide: "অটো-স্লাইড",
      intervalSeconds: "ইন্টারভাল (সেকেন্ড)",
      gradientFrom: "গ্রেডিয়েন্ট শুরু",
      gradientTo: "গ্রেডিয়েন্ট শেষ",
      content: "বিষয়বস্তু",
      background: "পটভূমি",
      imageUrl: "ছবি (URL)",
      caption: "ক্যাপশন",
      link: "লিংক",
      fullWidth: "ফুল-উইথ",
      videoUrl: "ভিডিও URL",
      question: "প্রশ্ন",
      answer: "উত্তর",
    },
    bgType: { solid: "কঠিন রং", gradient: "গ্রেডিয়েন্ট", image: "ছবি" },
    align: { left: "বামে", center: "মাঝে", right: "ডানে" },
    courseSource: { latest: "সর্বশেষ", popular: "জনপ্রিয়", manual: "ম্যানুয়াল নির্বাচন" },
    bg: { white: "সাদা", muted: "হালকা ধূসর" },
  },
  common: {
    comingSoon: "শীঘ্রই আসছে",
    comingSoonDesc: "এই অংশটি শীঘ্রই চালু হবে।",
    loading: "লোড হচ্ছে...",
    notFound: "পেজ খুঁজে পাওয়া যায়নি",
    backHome: "হোমে ফিরে যান",
    accessDenied: "অ্যাক্সেস নেই",
  },
  home: {
    welcome: "iCANBD-তে স্বাগতম",
    welcomeSub: "মান-সম্পন্ন কোর্স ও শিক্ষাসামগ্রী এক জায়গায়।",
    seeCourses: "কোর্স দেখুন",
    seeAllCourses: "সব কোর্স দেখুন",
    seeAllProducts: "সব প্রোডাক্ট দেখুন",
    seeAllNotices: "সব নোটিশ দেখুন",
    readMore: "আরও পড়ুন",
    details: "বিস্তারিত দেখুন",
    by: "শিক্ষক",
    duration: "সময়কাল",
    free: "বিনামূল্যে",
    noCourses: "এখনো কোনো কোর্স যোগ করা হয়নি।",
    noProducts: "এখনো কোনো প্রোডাক্ট যোগ করা হয়নি।",
    noNotices: "এখনো কোনো নোটিশ নেই।",
    prev: "পূর্ববর্তী",
    next: "পরবর্তী",
    students: "শিক্ষার্থী",
  },
  courses: {
    breadcrumbHome: "হোম",
    breadcrumbCourses: "কোর্সসমূহ",
    pageTitle: "সকল কোর্স",
    pageSubtitle: "আপনার পছন্দের কোর্স খুঁজুন এবং আজই শেখা শুরু করুন",
    searchPlaceholder: "কোর্স খুঁজুন...",
    category: "ক্যাটাগরি",
    allCategories: "সব ক্যাটাগরি",
    sortBy: "সাজানো",
    sortNewest: "নতুন আগে",
    sortPriceAsc: "দাম: কম থেকে বেশি",
    sortPriceDesc: "দাম: বেশি থেকে কম",
    empty: "কোনো কোর্স পাওয়া যায়নি",
    emptyDesc: "অন্য কীওয়ার্ড বা ফিল্টার দিয়ে চেষ্টা করুন।",
    showing: "মোট",
    coursesUnit: "টি কোর্স",
  },
  products: {
    breadcrumbHome: "হোম",
    breadcrumbProducts: "প্রোডাক্ট",
    pageTitle: "সকল প্রোডাক্ট",
    pageSubtitle: "শিক্ষাসামগ্রী, বই, নোট ও আনুষঙ্গিক — সবকিছু এক জায়গায়।",
    searchPlaceholder: "প্রোডাক্ট খুঁজুন...",
    empty: "কোনো প্রোডাক্ট পাওয়া যায়নি",
    emptyDesc: "অন্য কীওয়ার্ড দিয়ে চেষ্টা করুন।",
    showing: "মোট",
    productsUnit: "টি প্রোডাক্ট",
  },
  productDetail: {
    notFoundTitle: "প্রোডাক্টটি পাওয়া যায়নি",
    notFoundDesc: "অনুরোধকৃত প্রোডাক্টটি আর উপলব্ধ নেই বা সরিয়ে নেয়া হয়েছে।",
    backToProducts: "প্রোডাক্ট তালিকায় ফিরে যান",
    viewImage: "ছবি দেখুন",
    orderNow: "অর্ডার করুন",
    deliveryTitle: "ডেলিভারি তথ্য",
    deliveryDefault: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    contactTitle: "যোগাযোগ",
    contactDefault: "অর্ডার সংক্রান্ত যোগাযোগ: ০১৭০০-০০০০০০",
    detailsTitle: "প্রোডাক্ট সম্পর্কে বিস্তারিত",
    relatedTitle: "সম্পর্কিত প্রোডাক্ট",
  },
  courseDetail: {
    notFoundTitle: "কোর্সটি পাওয়া যায়নি",
    notFoundDesc: "অনুরোধকৃত কোর্সটি আর উপলব্ধ নেই বা সরিয়ে নেয়া হয়েছে।",
    backToCourses: "কোর্স তালিকায় ফিরে যান",
    lessonsUnit: "টি লেসন",
    enrolledStudents: "জন শিক্ষার্থী",
    discountBadge: "ছাড়!",
    offerEndsIn: "অফার শেষ হবে",
    days: "দিন",
    hours: "ঘণ্টা",
    minutes: "মিনিট",
    seconds: "সেকেন্ড",
    buyNow: "এখনই কিনুন",
    enroll: "ভর্তি হোন",
    moneyBack: "৩০ দিনের মানি-ব্যাক গ্যারান্টি",
    youGet: "কোর্সে যা যা পাচ্ছেন:",
    videos: "ভিডিও লেসন",
    pdfs: "PDF রিসোর্স",
    quizzes: "কুইজ",
    assignments: "অ্যাসাইনমেন্ট",
    lifetimeAccess: "আজীবন অ্যাক্সেস",
    certificate: "কোর্স সম্পন্নের সার্টিফিকেট",
    curriculumTitle: "কোর্স কারিকুলাম",
    detailsTitle: "কোর্স সম্পর্কে বিস্তারিত",
    showMore: "আরও পড়ুন",
    showLess: "কম দেখান",
    teacherTitle: "শিক্ষক পরিচিতি",
    reviewsTitle: "শিক্ষার্থীদের মতামত",
    averageRating: "গড় রেটিং",
    ratingsUnit: "টি রেটিং",
    relatedTitle: "আমাদের আরও কিছু কোর্স",
    preview: "প্রিভিউ",
    locked: "লক",
    moduleUnit: "মডিউল",
  },
} as const;
