import type {
  Course,
  CourseIncludes,
  CourseReview,
  Module,
  Teacher,
} from "./types";

const sampleTeacher = (name: string, short: string): Teacher => ({
  name,
  short_bio: short,
  long_bio:
    `${name} একজন অভিজ্ঞ শিক্ষক, যিনি গত ১০ বছর ধরে এই বিষয়ে কাজ করছেন। ` +
    "তিনি দেশ-বিদেশের অনেক প্রতিষ্ঠানে প্রশিক্ষণ দিয়েছেন এবং হাজারো শিক্ষার্থীকে সফল ক্যারিয়ার গড়তে সহায়তা করেছেন।",
});

const baseIncludes: CourseIncludes = {
  videos: 48,
  pdfs: 12,
  quizzes: 8,
  assignments: 5,
  lifetime_access: true,
  certificate: true,
};

function buildModules(): Module[] {
  return [
    {
      id: "m1",
      title: "শুরুর কথা ও পরিচিতি",
      total_duration: "১ ঘণ্টা ২০ মিনিট",
      lessons: [
        { id: "l1", title: "কোর্স পরিচিতি", type: "video", duration: "০৮:১২", isPreview: true },
        { id: "l2", title: "কীভাবে কোর্সটি ব্যবহার করবেন", type: "video", duration: "১০:০৫", isPreview: true },
        { id: "l3", title: "প্রয়োজনীয় গাইড (PDF)", type: "pdf", duration: "—" },
        { id: "l4", title: "প্রাথমিক ধারণা যাচাই", type: "quiz", duration: "১০ প্রশ্ন" },
      ],
    },
    {
      id: "m2",
      title: "মূল ভিত্তি গড়ে তোলা",
      total_duration: "৩ ঘণ্টা",
      lessons: [
        { id: "l5", title: "মৌলিক ধারণা — পর্ব ১", type: "video", duration: "১৮:৪০" },
        { id: "l6", title: "মৌলিক ধারণা — পর্ব ২", type: "video", duration: "২২:১০" },
        { id: "l7", title: "অনুশীলন: ছোট প্রজেক্ট", type: "assignment", duration: "—" },
        { id: "l8", title: "রিভিউ কুইজ", type: "quiz", duration: "১৫ প্রশ্ন" },
      ],
    },
    {
      id: "m3",
      title: "অ্যাডভান্সড টপিক",
      total_duration: "৪ ঘণ্টা ৩০ মিনিট",
      lessons: [
        { id: "l9", title: "অ্যাডভান্সড টেকনিক", type: "video", duration: "২৮:৫০" },
        { id: "l10", title: "কেস স্টাডি বিশ্লেষণ", type: "video", duration: "৩৫:২০" },
        { id: "l11", title: "রেফারেন্স গাইড (PDF)", type: "pdf", duration: "—" },
        { id: "l12", title: "ফাইনাল অ্যাসাইনমেন্ট", type: "assignment", duration: "—" },
      ],
    },
    {
      id: "m4",
      title: "প্রজেক্ট ও সার্টিফিকেট",
      total_duration: "২ ঘণ্টা",
      lessons: [
        { id: "l13", title: "ক্যাপস্টোন প্রজেক্ট পরিচিতি", type: "video", duration: "১৫:০০" },
        { id: "l14", title: "প্রজেক্ট গাইডলাইন (PDF)", type: "pdf", duration: "—" },
        { id: "l15", title: "ফাইনাল মূল্যায়ন", type: "quiz", duration: "৩০ প্রশ্ন" },
      ],
    },
  ];
}

const baseReviews: CourseReview[] = [
  {
    id: "r1",
    name: "তানভীর আহমেদ",
    rating: 5,
    comment: "অসাধারণ কোর্স! প্রতিটি বিষয় বিস্তারিতভাবে বুঝিয়ে দেয়া হয়েছে।",
    created_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "r2",
    name: "ফারহানা ইসলাম",
    rating: 5,
    comment: "কোর্সটি করে আমি আমার লক্ষ্যে পৌঁছাতে পেরেছি। সবাইকে রিকমেন্ড করব।",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "r3",
    name: "সাব্বির হোসেন",
    rating: 4,
    comment: "ভালো কোর্স, তবে আরও কিছু প্র্যাকটিক্যাল উদাহরণ থাকলে আরও ভালো হতো।",
    created_at: "2026-01-30T10:00:00Z",
  },
];

const longDescription = `এই কোর্সটি শূন্য থেকে শুরু করে অ্যাডভান্সড পর্যায় পর্যন্ত সাজানো হয়েছে।

কোর্সটি যে কারণে আলাদা:
• বাস্তব প্রজেক্ট-ভিত্তিক শেখা
• আজীবন অ্যাক্সেস
• বাংলায় বিস্তারিত ব্যাখ্যা
• সার্টিফিকেট প্রদান`;

const baseHighlights: string[] = [
  "বাস্তব প্রজেক্ট-ভিত্তিক শেখা",
  "আজীবন অ্যাক্সেস",
  "বাংলায় বিস্তারিত ব্যাখ্যা",
  "সার্টিফিকেট প্রদান",
];

// ─── ISSB Courses ────────────────────────────────────────────────────────────

export const ISSB_COURSES: Course[] = [
  {
    id: "issb1",
    title: "ISSB Written Test Complete Preparation",
    slug: "issb-written-test",
    category: "ISSB",
    thumbnail_url:
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&auto=format&fit=crop",
    duration: "৩০ ঘণ্টা",
    total_lessons: 45,
    price: 3500,
    discount_price: 2499,
    discount_ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
    teacher_name: "মেজর (অব.) আরিফ হোসেন",
    teacher: sampleTeacher("মেজর (অব.) আরিফ হোসেন", "সাবেক সেনা কর্মকর্তা, ISSB বিশেষজ্ঞ"),
    short_description: "ISSB লিখিত পরীক্ষার সকল বিষয় — বাংলা, ইংরেজি, গণিত, সাধারণ জ্ঞান সম্পূর্ণ প্রস্তুতি।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 2140,
    rating_average: 4.9,
    rating_count: 540,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-04-10T10:00:00Z",
  },
  {
    id: "issb2",
    title: "ISSB Psychological Test Mastery",
    slug: "issb-psychological-test",
    category: "ISSB",
    thumbnail_url:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&auto=format&fit=crop",
    duration: "২০ ঘণ্টা",
    total_lessons: 32,
    price: 2500,
    teacher_name: "ড. নাহিদ সুলতান",
    teacher: sampleTeacher("ড. নাহিদ সুলতান", "মনোবিজ্ঞানী, ISSB পরামর্শদাতা"),
    short_description: "Word Association, Thematic Apperception Test, Situation Reaction Test — সম্পূর্ণ গাইড।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 1860,
    rating_average: 4.8,
    rating_count: 420,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-03-25T10:00:00Z",
  },
  {
    id: "issb3",
    title: "ISSB Group Tasks & Command Task",
    slug: "issb-group-command-task",
    category: "ISSB",
    thumbnail_url:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&auto=format&fit=crop",
    duration: "১৫ ঘণ্টা",
    total_lessons: 24,
    price: 2000,
    discount_price: 1499,
    teacher_name: "ক্যাপ্টেন (অব.) ফয়সাল আহমেদ",
    teacher: sampleTeacher("ক্যাপ্টেন (অব.) ফয়সাল আহমেদ", "লিডারশিপ ট্রেইনার"),
    short_description: "Group Planning, Progressive Group Task, Half Group Task ও Command Task সফলভাবে পার করার কৌশল।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 1540,
    rating_average: 4.7,
    rating_count: 310,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "issb4",
    title: "ISSB Interview & Lecturette Skills",
    slug: "issb-interview-lecturette",
    category: "ISSB",
    thumbnail_url:
      "https://images.unsplash.com/photo-1560439513-74b037a25d84?w=1200&auto=format&fit=crop",
    duration: "১২ ঘণ্টা",
    total_lessons: 20,
    price: 1800,
    teacher_name: "কর্নেল (অব.) মাহবুব রহমান",
    teacher: sampleTeacher("কর্নেল (অব.) মাহবুব রহমান", "সাবেক সেনা কর্মকর্তা"),
    short_description: "IO Interview-এ সফল হওয়ার কৌশল, Lecturette বিষয় নির্বাচন ও উপস্থাপনা।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 1320,
    rating_average: 4.8,
    rating_count: 280,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-02-28T10:00:00Z",
  },
  {
    id: "issb5",
    title: "ISSB Physical Fitness Program",
    slug: "issb-physical-fitness",
    category: "ISSB",
    thumbnail_url:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&auto=format&fit=crop",
    duration: "১০ ঘণ্টা",
    total_lessons: 18,
    price: 0,
    teacher_name: "পিটি ইন্সট্রাক্টর রাসেল মিয়া",
    teacher: sampleTeacher("পিটি ইন্সট্রাক্টর রাসেল মিয়া", "ফিটনেস বিশেষজ্ঞ"),
    short_description: "ISSB শারীরিক পরীক্ষার জন্য সম্পূর্ণ ফিটনেস রুটিন — দৌড়, পুশ-আপ, পুল-আপ সব কিছু।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 3200,
    rating_average: 4.9,
    rating_count: 720,
    modules: buildModules(),
    includes: { ...baseIncludes, certificate: false },
    reviews: baseReviews,
    created_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "issb6",
    title: "ISSB Current Affairs & GK Crash Course",
    slug: "issb-current-affairs-gk",
    category: "ISSB",
    thumbnail_url:
      "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&auto=format&fit=crop",
    duration: "৮ ঘণ্টা",
    total_lessons: 16,
    price: 1200,
    discount_price: 899,
    teacher_name: "মেজর (অব.) আরিফ হোসেন",
    teacher: sampleTeacher("মেজর (অব.) আরিফ হোসেন", "ISSB বিশেষজ্ঞ"),
    short_description: "সাম্প্রতিক ঘটনা, বাংলাদেশ সেনাবাহিনী, মুক্তিযুদ্ধ ও আন্তর্জাতিক বিষয়াবলি।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 980,
    rating_average: 4.6,
    rating_count: 190,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-04-15T10:00:00Z",
  },
  {
    id: "issb7",
    title: "ISSB Complete Bundle (All-in-One)",
    slug: "issb-complete-bundle",
    category: "ISSB",
    thumbnail_url:
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&auto=format&fit=crop",
    duration: "৮০ ঘণ্টা",
    total_lessons: 120,
    price: 9999,
    discount_price: 5999,
    discount_ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    teacher_name: "মেজর (অব.) আরিফ হোসেন",
    teacher: sampleTeacher("মেজর (অব.) আরিফ হোসেন", "ISSB বিশেষজ্ঞ"),
    short_description: "লিখিত, মনস্তাত্ত্বিক, গ্রুপ টাস্ক, ইন্টারভিউ — সবকিছু এক প্যাকেজে। ISSB-তে সফল হওয়ার নিশ্চিত গাইড।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 4500,
    rating_average: 4.9,
    rating_count: 1200,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-04-20T10:00:00Z",
  },
  {
    id: "issb8",
    title: "ISSB Mock Test Series",
    slug: "issb-mock-test",
    category: "ISSB",
    thumbnail_url:
      "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=1200&auto=format&fit=crop",
    duration: "১৬ ঘণ্টা",
    total_lessons: 30,
    price: 1500,
    teacher_name: "ড. নাহিদ সুলতান",
    teacher: sampleTeacher("ড. নাহিদ সুলতান", "মনোবিজ্ঞানী"),
    short_description: "পূর্ণাঙ্গ মডেল টেস্ট ও বিস্তারিত ব্যাখ্যাসহ সমাধান। পরীক্ষার আগে নিজেকে যাচাই করুন।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 760,
    rating_average: 4.7,
    rating_count: 160,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-03-10T10:00:00Z",
  },
];

// ─── Cadet College Courses ────────────────────────────────────────────────────

export const CADET_COURSES: Course[] = [
  {
    id: "cadet1",
    title: "ক্যাডেট কলেজ ভর্তি পরীক্ষা: গণিত সম্পূর্ণ প্রস্তুতি",
    slug: "cadet-math",
    category: "Cadet",
    thumbnail_url:
      "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=1200&auto=format&fit=crop",
    duration: "৩৫ ঘণ্টা",
    total_lessons: 55,
    price: 3000,
    discount_price: 2199,
    discount_ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4).toISOString(),
    teacher_name: "মোহাম্মদ জাহিদুল ইসলাম",
    teacher: sampleTeacher("মোহাম্মদ জাহিদুল ইসলাম", "গণিত শিক্ষক, ২০+ বছরের অভিজ্ঞতা"),
    short_description: "বীজগণিত, জ্যামিতি, পাটিগণিত — ক্যাডেট কলেজ ভর্তির পূর্ণ গণিত সিলেবাস।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 3400,
    rating_average: 4.9,
    rating_count: 870,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-04-18T10:00:00Z",
  },
  {
    id: "cadet2",
    title: "ক্যাডেট কলেজ ইংরেজি মাস্টারক্লাস",
    slug: "cadet-english",
    category: "Cadet",
    thumbnail_url:
      "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=1200&auto=format&fit=crop",
    duration: "২৫ ঘণ্টা",
    total_lessons: 40,
    price: 2500,
    teacher_name: "শাহানা পারভীন",
    teacher: sampleTeacher("শাহানা পারভীন", "ইংরেজি শিক্ষক, ক্যাডেট বিশেষজ্ঞ"),
    short_description: "Grammar, Composition, Reading Comprehension — ক্যাডেট ভর্তির ইংরেজি সম্পূর্ণ প্রস্তুতি।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 2900,
    rating_average: 4.8,
    rating_count: 640,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-04-12T10:00:00Z",
  },
  {
    id: "cadet3",
    title: "ক্যাডেট কলেজ বিজ্ঞান প্রস্তুতি",
    slug: "cadet-science",
    category: "Cadet",
    thumbnail_url:
      "https://images.unsplash.com/photo-1532094349884-543559059c7d?w=1200&auto=format&fit=crop",
    duration: "২০ ঘণ্টা",
    total_lessons: 35,
    price: 2000,
    discount_price: 1599,
    teacher_name: "ড. রফিকুল ইসলাম",
    teacher: sampleTeacher("ড. রফিকুল ইসলাম", "বিজ্ঞান শিক্ষক"),
    short_description: "পদার্থ, রসায়ন ও জীববিজ্ঞান — ক্যাডেট কলেজ বিজ্ঞান অংশের সম্পূর্ণ গাইড।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 2100,
    rating_average: 4.7,
    rating_count: 480,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-04-05T10:00:00Z",
  },
  {
    id: "cadet4",
    title: "ক্যাডেট কলেজ বাংলা ও সাধারণ জ্ঞান",
    slug: "cadet-bangla-gk",
    category: "Cadet",
    thumbnail_url:
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&auto=format&fit=crop",
    duration: "১৮ ঘণ্টা",
    total_lessons: 30,
    price: 1800,
    teacher_name: "মোহাম্মদ জাহিদুল ইসলাম",
    teacher: sampleTeacher("মোহাম্মদ জাহিদুল ইসলাম", "শিক্ষক"),
    short_description: "বাংলা ব্যাকরণ, রচনা, বাংলাদেশ ও আন্তর্জাতিক সাধারণ জ্ঞান সম্পূর্ণ কোর্স।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 1800,
    rating_average: 4.6,
    rating_count: 360,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-03-30T10:00:00Z",
  },
  {
    id: "cadet5",
    title: "ক্যাডেট কলেজ মৌখিক পরীক্ষা প্রস্তুতি",
    slug: "cadet-oral-test",
    category: "Cadet",
    thumbnail_url:
      "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&auto=format&fit=crop",
    duration: "১০ ঘণ্টা",
    total_lessons: 18,
    price: 0,
    teacher_name: "শাহানা পারভীন",
    teacher: sampleTeacher("শাহানা পারভীন", "মৌখিক পরীক্ষা বিশেষজ্ঞ"),
    short_description: "মৌখিক পরীক্ষায় আত্মবিশ্বাসের সাথে উত্তর দেওয়ার কৌশল ও নমুনা প্রশ্নোত্তর।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 4100,
    rating_average: 4.9,
    rating_count: 950,
    modules: buildModules(),
    includes: { ...baseIncludes, certificate: false },
    reviews: baseReviews,
    created_at: "2026-04-08T10:00:00Z",
  },
  {
    id: "cadet6",
    title: "ক্যাডেট কলেজ শারীরিক ফিটনেস কোর্স",
    slug: "cadet-physical",
    category: "Cadet",
    thumbnail_url:
      "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=1200&auto=format&fit=crop",
    duration: "৮ ঘণ্টা",
    total_lessons: 15,
    price: 1000,
    teacher_name: "পিটি ইন্সট্রাক্টর রাসেল মিয়া",
    teacher: sampleTeacher("পিটি ইন্সট্রাক্টর রাসেল মিয়া", "ফিটনেস বিশেষজ্ঞ"),
    short_description: "ক্যাডেট কলেজ শারীরিক পরীক্ষার জন্য বিশেষ ফিটনেস প্ল্যান ও ব্যায়ামের রুটিন।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 2600,
    rating_average: 4.7,
    rating_count: 510,
    modules: buildModules(),
    includes: { ...baseIncludes, certificate: false },
    reviews: baseReviews,
    created_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "cadet7",
    title: "ক্যাডেট কলেজ সম্পূর্ণ প্যাকেজ",
    slug: "cadet-complete-bundle",
    category: "Cadet",
    thumbnail_url:
      "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&auto=format&fit=crop",
    duration: "৯৫ ঘণ্টা",
    total_lessons: 180,
    price: 8999,
    discount_price: 4999,
    discount_ends_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 6).toISOString(),
    teacher_name: "মোহাম্মদ জাহিদুল ইসলাম",
    teacher: sampleTeacher("মোহাম্মদ জাহিদুল ইসলাম", "শিক্ষক"),
    short_description: "গণিত, বিজ্ঞান, বাংলা, ইংরেজি, সাধারণ জ্ঞান, মৌখিক ও শারীরিক — সব প্রস্তুতি এক প্যাকেজে।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 5800,
    rating_average: 4.9,
    rating_count: 1500,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-04-22T10:00:00Z",
  },
  {
    id: "cadet8",
    title: "ক্যাডেট কলেজ মডেল টেস্ট সিরিজ",
    slug: "cadet-model-test",
    category: "Cadet",
    thumbnail_url:
      "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=1200&auto=format&fit=crop",
    duration: "১৪ ঘণ্টা",
    total_lessons: 25,
    price: 1500,
    discount_price: 999,
    teacher_name: "শাহানা পারভীন",
    teacher: sampleTeacher("শাহানা পারভীন", "শিক্ষক"),
    short_description: "পূর্ণাঙ্গ মডেল পরীক্ষা ও বিস্তারিত সমাধান। আসল পরীক্ষার আগে নিজেকে পরীক্ষা করুন।",
    long_description: longDescription,
    highlights: baseHighlights,
    enrollment_count: 1400,
    rating_average: 4.8,
    rating_count: 290,
    modules: buildModules(),
    includes: baseIncludes,
    reviews: baseReviews,
    created_at: "2026-04-01T10:00:00Z",
  },
];

// Combined export for useCourses hook (courses page shows all)
export const MOCK_COURSES: Course[] = [...ISSB_COURSES, ...CADET_COURSES];
