import type { Product } from "./types";

export const mockProducts: Product[] = [
  // ─── iCAN Guide Practice Sheets ───────────────────────────────────────────
  {
    id: "ican-guide-class-5",
    slug: "ican-guide-academic-practice-sheets-class-5",
    name: "iCAN Guide — Academic Practice Sheets (Class 5)",
    category: "বই",
    image_url: "/products/book-class5-v2.jpg",
    images: [
      "/products/book-class5-v2.jpg",
      "/products/book-class5-v3.jpg",
      "/products/book-class5-v1.png",
    ],
    price: 400,
    discount_price: 320,
    short_description:
      "iCAN Guide Academic Practice Sheets — ৫ম শ্রেণির শিক্ষার্থীদের জন্য ক্যাডেট কলেজ ভর্তি প্রস্তুতির বিশেষ প্র্যাকটিস শিট সংকলন।",
    long_description: `iCAN Academy-র বিশেষজ্ঞ শিক্ষক প্যানেল কর্তৃক প্রণীত Academic Practice Sheets — ৫ম শ্রেণির শিক্ষার্থীদের জন্য।

বইয়ের বিশেষত্ব:
• ক্যাডেট কলেজ ভর্তি পরীক্ষার আদলে সাজানো প্র্যাকটিস শিট
• বাংলা, ইংরেজি, গণিত ও সাধারণ জ্ঞান — সব বিষয় একসাথে
• অধ্যায়ভিত্তিক বিন্যাস ও বিস্তারিত সমাধান
• iCAN-এর অভিজ্ঞ শিক্ষকদের তত্ত্বাবধানে প্রস্তুত`,
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    contact_info: "অর্ডার: ০১৮৯৪৭৩৪০০২",
    in_stock: true,
    sales_count: 640,
    created_at: "2026-05-20T08:00:00Z",
  },
  {
    id: "ican-guide-class-6",
    slug: "ican-guide-academic-practice-sheets-class-6",
    name: "iCAN Guide — Academic Practice Sheets (Class 6)",
    category: "বই",
    image_url: "/products/book-class6-v2.jpg",
    images: [
      "/products/book-class6-v2.jpg",
      "/products/book-class6-v1.png",
    ],
    price: 400,
    discount_price: 320,
    short_description:
      "iCAN Guide Academic Practice Sheets — ৬ষ্ঠ শ্রেণির শিক্ষার্থীদের জন্য ক্যাডেট কলেজ ভর্তি প্রস্তুতির বিশেষ প্র্যাকটিস শিট সংকলন।",
    long_description: `iCAN Academy-র বিশেষজ্ঞ শিক্ষক প্যানেল কর্তৃক প্রণীত Academic Practice Sheets — ৬ষ্ঠ শ্রেণির শিক্ষার্থীদের জন্য।

বইয়ের বিশেষত্ব:
• ক্যাডেট কলেজ ভর্তি পরীক্ষার আদলে সাজানো প্র্যাকটিস শিট
• বাংলা, ইংরেজি, গণিত ও সাধারণ জ্ঞান — সব বিষয় একসাথে
• অধ্যায়ভিত্তিক বিন্যাস ও বিস্তারিত সমাধান
• iCAN-এর অভিজ্ঞ শিক্ষকদের তত্ত্বাবধানে প্রস্তুত`,
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    contact_info: "অর্ডার: ০১৮৯৪৭৩৪০০২",
    in_stock: true,
    sales_count: 580,
    created_at: "2026-05-20T08:00:00Z",
  },
  {
    id: "p1",
    slug: "issb-complete-guide-book",
    name: "ISSB সম্পূর্ণ গাইড বই",
    category: "বই",
    image_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    price: 850,
    discount_price: 599,
    short_description: "ISSB-র লিখিত, মনস্তাত্ত্বিক, গ্রুপ টাস্ক ও ইন্টারভিউ — সব ধাপের সম্পূর্ণ গাইড।",
    long_description: "এই বইয়ে ISSB-র প্রতিটি ধাপের বিস্তারিত আলোচনা, কৌশল ও নমুনা প্রশ্নোত্তর রয়েছে।",
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    contact_info: "অর্ডার: ০১৭০০-০০০০০০",
    in_stock: true,
    sales_count: 1240,
    created_at: "2026-04-01T08:00:00Z",
  },
  {
    id: "p2",
    slug: "issb-psychological-test-book",
    name: "ISSB সাইকোলজিক্যাল টেস্ট বই",
    category: "বই",
    image_url: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=800&q=80",
    price: 650,
    discount_price: 449,
    short_description: "WAT, TAT, SRT ও SDT — ISSB মনস্তাত্ত্বিক পরীক্ষার সম্পূর্ণ প্রস্তুতি বই।",
    long_description: "এই বইয়ে ISSB-র চারটি মনস্তাত্ত্বিক পরীক্ষার জন্য বিস্তারিত কৌশল ও প্রচুর অনুশীলনী রয়েছে।",
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    contact_info: "অর্ডার: ০১৭০০-০০০০০০",
    in_stock: true,
    sales_count: 980,
    created_at: "2026-03-20T08:00:00Z",
  },
  {
    id: "p3",
    slug: "issb-question-bank",
    name: "ISSB প্রশ্নব্যাংক (বিগত ১০ বছর)",
    category: "প্রশ্নব্যাংক",
    image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80",
    price: 750,
    discount_price: 549,
    short_description: "বিগত ১০ বছরের ISSB লিখিত পরীক্ষার প্রশ্ন ও সমাধান একটি বইয়ে।",
    long_description: "ISSB লিখিত পরীক্ষার বাংলা, ইংরেজি, গণিত ও সাধারণ জ্ঞানের বিগত প্রশ্নের সমাহার।",
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    in_stock: true,
    sales_count: 760,
    created_at: "2026-03-10T08:00:00Z",
  },
  {
    id: "p4",
    slug: "cadet-complete-guide",
    name: "ক্যাডেট কলেজ ভর্তি গাইড",
    category: "বই",
    image_url: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80",
    price: 700,
    discount_price: 499,
    short_description: "ক্যাডেট কলেজ ভর্তি পরীক্ষার সম্পূর্ণ গাইড — সকল বিষয় একটি বইয়ে।",
    long_description: "গণিত, বিজ্ঞান, বাংলা, ইংরেজি ও সাধারণ জ্ঞান — সব বিষয়ের সম্পূর্ণ প্রস্তুতি।",
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    contact_info: "অর্ডার: ০১৭০০-০০০০০০",
    in_stock: true,
    sales_count: 1560,
    created_at: "2026-04-05T08:00:00Z",
  },
  {
    id: "p5",
    slug: "cadet-math-guide",
    name: "ক্যাডেট কলেজ গণিত গাইড",
    category: "বই",
    image_url: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?auto=format&fit=crop&w=800&q=80",
    price: 550,
    short_description: "ক্যাডেট কলেজ ভর্তির গণিত অংশের বিস্তারিত সমাধানসহ গাইড বই।",
    long_description: "বীজগণিত, জ্যামিতি ও পাটিগণিতের সব টপিক অধ্যায়ভিত্তিকভাবে সাজানো।",
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    in_stock: true,
    sales_count: 890,
    created_at: "2026-03-25T08:00:00Z",
  },
  {
    id: "p6",
    slug: "cadet-question-bank",
    name: "ক্যাডেট কলেজ প্রশ্নব্যাংক",
    category: "প্রশ্নব্যাংক",
    image_url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=800&q=80",
    price: 680,
    discount_price: 480,
    short_description: "বিগত বছরের ক্যাডেট কলেজ ভর্তি পরীক্ষার প্রশ্ন ও বিস্তারিত সমাধান।",
    long_description: "সকল ক্যাডেট কলেজের বিগত প্রশ্নের সমাহার, বিস্তারিত সমাধান ও ব্যাখ্যাসহ।",
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    in_stock: true,
    sales_count: 1100,
    created_at: "2026-04-10T08:00:00Z",
  },
  {
    id: "p7",
    slug: "issb-note-set",
    name: "ISSB হ্যান্ডনোট সেট",
    category: "নোট",
    image_url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80",
    price: 420,
    discount_price: 299,
    short_description: "ISSB সম্পূর্ণ প্রস্তুতির জন্য হাতে লেখা হ্যান্ডনোট সেট — সহজ ও গোছানো।",
    long_description: "ISSB-র প্রতিটি ধাপের জন্য আলাদা হ্যান্ডনোট, গুরুত্বপূর্ণ পয়েন্টসহ।",
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    in_stock: true,
    sales_count: 640,
    created_at: "2026-03-15T08:00:00Z",
  },
  {
    id: "p8",
    slug: "cadet-note-set",
    name: "ক্যাডেট কলেজ হ্যান্ডনোট সেট",
    category: "নোট",
    image_url: "https://images.unsplash.com/photo-1554475901-4538ddfbccc2?auto=format&fit=crop&w=800&q=80",
    price: 380,
    discount_price: 269,
    short_description: "ক্যাডেট কলেজ ভর্তির সব বিষয়ের হ্যান্ডনোট একসাথে।",
    long_description: "গণিত, বিজ্ঞান, বাংলা ও ইংরেজির গুরুত্বপূর্ণ পয়েন্ট সম্বলিত হ্যান্ডনোট সেট।",
    delivery_info: "৩-৫ কর্মদিবসে সারাদেশে হোম ডেলিভারি।",
    in_stock: true,
    sales_count: 520,
    created_at: "2026-04-08T08:00:00Z",
  },
];
